// <auto-generated />
using System;
using FashionStore.DAL.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FashionStore.DAL.Migrations.AppDb
{
    [DbContext(typeof(AppDbContext))]

    [Migration("20250410125107_Test")]
    partial class Test
    {
        /// <inheritdoc />
    }
}
